apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  name: oncokb-sop
  namespace: test
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - image: nginx
              name: nginx
              ports:
              - containerPort: 80
  placement:
    clusters:
    - name: us-east
    - name: ap-northeast
---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedService
metadata:
  name: oncokb-sop
  namespace: test
spec:
  template:
    spec:
      selector:
        app: nginx
      type: ClusterIP
      ports:
      - name: http
        port: 80
  placement:
    clusters:
    - name: us-east
    - name: ap-northeast
