apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  name: oncokb-core
  namespace: test
spec:
  template:
    metadata:
      labels:
        app: oncokb-core
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: oncokb-core
      template:
        metadata:
          labels:
            app: oncokb-core
        spec:
          containers:
            - env:
              envFrom:
                - configMapRef:
                    name: oncokb-core
              image: cbioportal/oncokb:2.7.0
              command: ["java"]
              args: [
                # from https://developers.redhat.com/blog/2017/04/04/openjdk-and-containers/
                "-Xms250m",
                "-XX:+UseSerialGC",
                # aggressive garbage collection
                "-XX:MinHeapFreeRatio=20",
                "-XX:MaxHeapFreeRatio=40",
                "-XX:GCTimeRatio=4",
                "-XX:AdaptiveSizePolicyWeight=90",
                "-XX:+UnlockExperimentalVMOptions",
                "-XX:+UseCGroupMemoryLimitForHeap",
                # use maxRAMFraction > 1 https://github.com/akka/akka/issues/23499
                "-XX:MaxRAMFraction=2",
                "-XX:+PrintFlagsFinal",
                "-XshowSettings:vm",
                # need to set MaxRAM, somehow the MaxRAMFraction is not picked up
                # from the limits
                "-XX:MaxRAM=1024m",
                "-Djdbc.driverClassName=com.mysql.jdbc.Driver",
                "-Djdbc.url=jdbc:mysql://$(DB_HOST):3306/$(MYSQL_DATABASE)?useUnicode=yes&characterEncoding=UTF-8&useSSL=false",
                "-Djdbc.username=$(MYSQL_USER)",
                "-Djdbc.password=$(MYSQL_PASSWORD)",
                "-Ddata.version=v2.3",
                "-Ddata.version_date=05/11/2020",
                "-Dgenomenexus.api=https://www.genomenexus.org/",
                "-Doncokb_data.access_token=$(ONCOKB_DATA_ACCESS_TOKEN)",
                "-Dshow_sitemaps=false",
                "-jar",
                "/webapp-runner.jar",
                "--enable-compression",
                "--expand-war",
                "--port",
                "8888",
                "/app.war"
              ]
              imagePullPolicy: Always
              # use actionable variants endpoint to cache everything
              readinessProbe:
                httpGet:
                  path: /api/v1/utils/allActionableVariants
                  port: 8888
                initialDelaySeconds: 300
                timeoutSeconds: 10
                periodSeconds: 20
              livenessProbe:
                httpGet:
                  path: /api/v1/utils/allActionableVariants
                  port: 8888
                initialDelaySeconds: 30
                timeoutSeconds: 300
                periodSeconds: 200
              name: oncokb-core
              ports:
                - containerPort: 8888
                  protocol: TCP
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  memory: 2Gi
  placement:
    clusters:
    - name: us-east
    - name: ap-northeast
---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedService
metadata:
  name: oncokb-core
  namespace: test
spec:
  template:
    spec:
      ports:
      - port: 80
        name: http
        targetPort: 8888
      selector:
        run: oncokb-core
      type: ClusterIP
  placement:
    clusters:
    - name: us-east
    - name: ap-northeast
